---
- name: Add APT key for Grafana
  apt_key:
    url: https://packages.grafana.com/gpg.key
  when: ansible_distribution == "Ubuntu"

- name:  Add Grafana APT repository
  apt_repository:
     repo: deb https://packages.grafana.com/oss/deb stable main
     state: present
     filename: "{{ service }}" 
  when: ansible_distribution == "Ubuntu"

- name:  Update APT cache
  apt: 
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Grafana package using Apt
  apt: 
    name: "{{ service }}"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Copy Grafana Yum repository
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d
  #when: ansible_distribution == "RedHat"
  when: ansible_distribution in ['RedHat', 'CentOS']

- name:  Update yum cache
  yum: 
    update_cache: yes
  #when: ansible_distribution == "RedHat"
  when: ansible_distribution in ['RedHat', 'CentOS']

- name: Install Grafana package using Yum
  yum:
    name: "{{ service }}"
    state: present
  #when: ansible_distribution == "RedHat"
  when: ansible_distribution in ['RedHat', 'CentOS']
